// Module 13 - Binomial Distribution
const MODULE13_BINOMIAL_NOTES = {
    binomialDistribution: [
        {
            id: 131,
            title: "Binomial Distribution",
            category: "binomial-distribution",
            content: `<h3><strong>Binomial Distribution</strong></h3>
<p>The binomial probability distribution is a discrete probability distribution that has many applications. It is associated with a multiple-step experiment that we call the binomial experiment.</p>

<h4><strong>Properties of a Binomial Experiment</strong></h4>
<p>A binomial experiment exhibits the following four properties:</p>

<h5><strong>PROPERTIES OF A BINOMIAL EXPERIMENT</strong></h5>
<ol>
<li><strong>The experiment consists of a sequence of n identical trials.</strong></li>
<li><strong>Two outcomes are possible on each trial.</strong> We refer to one outcome as a success and the other outcome as a failure.</li>
<li><strong>The probability of a success, denoted by p, does not change from trial to trial.</strong> Consequently, the probability of a failure, denoted by 1 - p, does not change from trial to trial.</li>
<li><strong>The trials are independent.</strong></li>
</ol>

<h6><strong>Key Concepts:</strong></h6>
<ul>
<li><strong>Bernoulli Process:</strong> If properties 2, 3, and 4 are present, we say the trials are generated by a Bernoulli process</li>
<li><strong>Binomial Experiment:</strong> If, in addition, property 1 is present, we say we have a binomial experiment</li>
<li><strong>Random Variable:</strong> x = number of successes occurring in the n trials (x can assume values 0, 1, 2, 3, ..., n)</li>
</ul>

<h5><strong>Visual Representation of Binomial Experiment</strong></h5>
<p>Figure 5.2 depicts one possible sequence of successes and failures for a binomial experiment involving eight trials:</p>

<h6><strong>ONE POSSIBLE SEQUENCE OF SUCCESSES AND FAILURES FOR AN EIGHT-TRIAL BINOMIAL EXPERIMENT</strong></h6>
<ul>
<li><strong>Property 1:</strong> The experiment consists of n = 8 identical trials</li>
<li><strong>Property 2:</strong> Each trial results in either success (S) or failure (F)</li>
</ul>

` + Utils.createBlueTable(
    ['Trials', '1', '2', '3', '4', '5', '6', '7', '8'],
    ['Outcomes', 'S', 'F', 'F', 'S', 'S', 'F', 'S', 'S']
) + `

<h4><strong>Example: Coin Tossing Experiment</strong></h4>
<p>Consider the experiment of tossing a coin five times and observing whether the coin lands with a head or a tail on its upward face. We want to count the number of heads appearing over the five tosses.</p>

<h5><strong>Checking Binomial Properties:</strong></h5>
<ol>
<li><strong>Identical trials:</strong> The experiment consists of five identical trials; each trial involves the tossing of one coin.</li>
<li><strong>Two outcomes:</strong> Two outcomes are possible for each trial: a head or a tail. We can designate head as success and tail as failure.</li>
<li><strong>Constant probability:</strong> The probability of a head and the probability of a tail are the same for each trial, with p = 0.5 and 1 - p = 0.5.</li>
<li><strong>Independent trials:</strong> The trials or tosses are independent because the outcome on any one trial is not affected by what happens on other trials.</li>
</ol>

<p><strong>Result:</strong> All four properties are satisfied, so this is a binomial experiment.</p>
<p><strong>Random Variable:</strong> x = the number of heads appearing in the five trials (x can assume values 0, 1, 2, 3, 4, or 5)</p>

<h4><strong>Example: Insurance Sales Problem</strong></h4>
<p>An insurance salesperson visits 10 randomly selected families. The outcome associated with each visit is classified as a success if the family purchases an insurance policy and a failure if the family does not. From past experience, the salesperson knows the probability that a randomly selected family will purchase an insurance policy is 0.10.</p>

<h5><strong>Checking Binomial Properties:</strong></h5>
<ol>
<li><strong>Identical trials:</strong> The experiment consists of 10 identical trials; each trial involves contacting one family.</li>
<li><strong>Two outcomes:</strong> Two outcomes are possible on each trial: the family purchases a policy (success) or the family does not purchase a policy (failure).</li>
<li><strong>Constant probability:</strong> The probabilities of a purchase and a nonpurchase are assumed to be the same for each sales call, with p = 0.10 and 1 - p = 0.90.</li>
<li><strong>Independent trials:</strong> The trials are independent because the families are randomly selected.</li>
</ol>

<p><strong>Result:</strong> All four properties are satisfied, so this is a binomial experiment.</p>
<p><strong>Random Variable:</strong> x = the number of sales obtained in contacting the 10 families (x can assume values 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, and 10)</p>

<h4><strong>Important Distinctions</strong></h4>
<p><strong>Property 3 (Stationarity):</strong> The probability of success does not change from trial to trial. This is sometimes confused with Property 4 (Independence).</p>

<p><strong>Example:</strong> If the salesperson gets tired and loses enthusiasm, the probability of success might drop from 0.10 to 0.05 by the tenth call. In such a case, Property 3 would not be satisfied, and we would not have a binomial experiment, even if Property 4 (independence) held.</p>

<h4><strong>Martin Clothing Store Problem</strong></h4>
<p>Let us consider the purchase decisions of the next three customers who enter the Martin Clothing Store. On the basis of past experience, the store manager estimates the probability that any one customer will make a purchase is 0.30. What is the probability that two of the next three customers will make a purchase?</p>

<h5><strong>Tree Diagram Analysis</strong></h5>
<p>Using a tree diagram, we can see that the experiment of observing the three customers each making a purchase decision has eight possible outcomes. Using S to denote success (a purchase) and F to denote failure (no purchase), we are interested in experimental outcomes involving two successes in the three trials.</p>

<h6><strong>TREE DIAGRAM FOR THE MARTIN CLOTHING STORE PROBLEM</strong></h6>
<p><strong>First Customer → Second Customer → Third Customer → Experimental Outcome → Value of x</strong></p>
<ul>
<li>S → S → S → (S, S, S) → 3</li>
<li>S → S → F → (S, S, F) → 2</li>
<li>S → F → S → (S, F, S) → 2</li>
<li>S → F → F → (S, F, F) → 1</li>
<li>F → S → S → (F, S, S) → 2</li>
<li>F → S → F → (F, S, F) → 1</li>
<li>F → F → S → (F, F, S) → 1</li>
<li>F → F → F → (F, F, F) → 0</li>
</ul>

<p><strong>Where:</strong> S = Purchase, F = No purchase, x = Number of customers making a purchase</p>

<h5><strong>Verifying Binomial Properties:</strong></h5>
<ol>
<li><strong>Identical trials:</strong> The experiment can be described as a sequence of three identical trials, one trial for each of the three customers who will enter the store.</li>
<li><strong>Two outcomes:</strong> Two outcomes are possible for each trial: the customer makes a purchase (success) or the customer does not make a purchase (failure).</li>
<li><strong>Constant probability:</strong> The probability that the customer will make a purchase (0.30) or will not make a purchase (0.70) is assumed to be the same for all customers.</li>
<li><strong>Independent trials:</strong> The purchase decision of each customer is independent of the decisions of the other customers.</li>
</ol>

<p><strong>Result:</strong> All four properties are satisfied, so this is a binomial experiment.</p>

<h4><strong>Binomial Probability Function Development</strong></h4>
<p>The number of experimental outcomes resulting in exactly x successes in n trials can be computed using:</p>

<h5><strong>Number of Experimental Outcomes</strong></h5>
<p class="formula">C(n,x) = n! / [x!(n-x)!]</p>

<p>where:</p>
<ul>
<li>n! = n(n-1)(n-2)...(2)(1)</li>
<li>0! = 1 (by definition)</li>
</ul>

<h6><strong>Example Calculations:</strong></h6>
<p><strong>Number of ways to get 2 successes in 3 trials:</strong></p>
<p class="formula">C(3,2) = 3! / [2!(3-2)!] = 6 / [(2)(1)] = 3</p>

<p><strong>Number of ways to get 3 successes in 3 trials:</strong></p>
<p class="formula">C(3,3) = 3! / [3!(3-3)!] = 6 / [6(1)] = 1</p>

<h5><strong>Probability of a Particular Sequence</strong></h5>
<p>The probability of a particular sequence of trial outcomes with x successes in n trials is:</p>
<p class="formula">p^x(1-p)^(n-x)</p>

<h6><strong>Example:</strong></h6>
<p>For the Martin Clothing Store, any experimental outcome with two successes has a probability of:</p>
<p class="formula">p²(1-p)^(3-2) = p²(1-p)¹ = (0.30)²(0.70)¹ = 0.063</p>

<h5><strong>Binomial Probability Function</strong></h5>
<p class="formula">f(x) = C(n,x) × p^x(1-p)^(n-x)</p>

<p>where:</p>
<ul>
<li>x = the number of successes</li>
<li>p = the probability of a success on one trial</li>
<li>n = the number of trials</li>
<li>f(x) = the probability of x successes in n trials</li>
</ul>

<h4><strong>Calculating Probabilities for Martin Clothing Store</strong></h4>
<p>Using the binomial probability function with n = 3, p = 0.30:</p>

<p><strong>Probability of 0 purchases:</strong></p>
<p class="formula">f(0) = C(3,0) × (0.30)^0 × (0.70)^3 = 1 × 1 × 0.343 = 0.343</p>

<p><strong>Probability of 1 purchase:</strong></p>
<p class="formula">f(1) = C(3,1) × (0.30)^1 × (0.70)^2 = 3 × 0.30 × 0.49 = 0.441</p>

<p><strong>Probability of 2 purchases:</strong></p>
<p class="formula">f(2) = C(3,2) × (0.30)^2 × (0.70)^1 = 3 × 0.09 × 0.70 = 0.189</p>

<p><strong>Probability of 3 purchases:</strong></p>
<p class="formula">f(3) = C(3,3) × (0.30)^3 × (0.70)^0 = 1 × 0.027 × 1 = 0.027</p>

<h5><strong>Probability Distribution</strong></h5>
` + Utils.createBlueTable(
    ['x', 'f(x)'],
    [
        ['0', '0.343'],
        ['1', '0.441'],
        ['2', '0.189'],
        ['3', '0.027'],
        ['<strong>Total</strong>', '<strong>1.000</strong>']
    ]
) + `

<h4><strong>Using Tables of Binomial Probabilities</strong></h4>
<p>Tables have been developed that give the probability of x successes in n trials for a binomial experiment. These tables are generally easy to use and quicker than the formula.</p>

<h5><strong>Example: Using Tables</strong></h5>
<p>For n = 10, x = 4, p = 0.30, we can read f(4) = 0.2001 directly from the binomial probability table.</p>

<h5><strong>Selected Values from Binomial Probability Table</strong></h5>
<p><strong>Example:</strong> n = 10, x = 3, p = 0.40; f(3) = 0.2150</p>

<h6><strong>Note:</strong></h6>
<p>Even though the tables of binomial probabilities are relatively easy to use, it is impossible to have tables that show all possible values of n and p that might be encountered in a binomial experiment. However, with today's calculators, using the formula to calculate the desired probability is not difficult, especially if the number of trials is not large.</p>

<h4><strong>Expected Value and Variance for the Binomial Distribution</strong></h4>
<p>In the special case where the random variable has a binomial distribution with a known number of trials n and a known probability of success p, the general formulas for the expected value and variance can be simplified.</p>

<h5><strong>Formulas</strong></h5>
<p class="formula">E(x) = μ = np</p>
<p class="formula">Var(x) = σ² = np(1-p)</p>

<h5><strong>Example: Martin Clothing Store</strong></h5>
<p>For the Martin Clothing Store problem with three customers:</p>

<p><strong>Expected number of purchases:</strong></p>
<p class="formula">E(x) = np = 3(0.30) = 0.9</p>

<p><strong>Variance:</strong></p>
<p class="formula">Var(x) = np(1-p) = 3(0.30)(0.70) = 0.63</p>

<p><strong>Standard deviation:</strong></p>
<p class="formula">σ = √0.63 = 0.79</p>

<h5><strong>Business Application</strong></h5>
<p>Suppose that for the next month the Martin Clothing Store forecasts 1000 customers will enter the store. What is the expected number of customers who will make a purchase?</p>

<p><strong>Expected purchases:</strong></p>
<p class="formula">μ = np = (1000)(0.30) = 300</p>

<p><strong>Variance:</strong></p>
<p class="formula">σ² = np(1-p) = (1000)(0.30)(0.70) = 210</p>

<p><strong>Standard deviation:</strong></p>
<p class="formula">σ = √210 = 14.49</p>

<h6><strong>Business Insight:</strong></h6>
<p>To increase the expected number of purchases, Martin's must induce more customers to enter the store and/or somehow increase the probability that any individual customer will make a purchase after entering.</p>

<h4><strong>Business Applications</strong></h4>
<ul>
<li><strong>Quality Control:</strong> Number of defective items in a sample</li>
<li><strong>Marketing:</strong> Number of customers who respond to a promotion</li>
<li><strong>Finance:</strong> Number of successful trades in a series</li>
<li><strong>Healthcare:</strong> Number of patients who respond to treatment</li>
<li><strong>Manufacturing:</strong> Number of products that pass inspection</li>
<li><strong>Sales:</strong> Number of successful sales calls</li>
<li><strong>Research:</strong> Number of successful experiments</li>
</ul>

<h4><strong>Key Insights</strong></h4>
<ul>
<li><strong>Four Properties:</strong> Must be satisfied for binomial experiment</li>
<li><strong>Success/Failure:</strong> Clearly define what constitutes success</li>
<li><strong>Constant Probability:</strong> p must remain the same across trials</li>
<li><strong>Independence:</strong> Trials must not influence each other</li>
<li><strong>Expected Value:</strong> Simple formula μ = np</li>
<li><strong>Variance:</strong> Simple formula σ² = np(1-p)</li>
<li><strong>Applications:</strong> Widely used in business and statistics</li>
<li><strong>Tree Diagrams:</strong> Help visualize all possible outcomes</li>
<li><strong>Combinatorial Formula:</strong> C(n,x) counts successful outcomes</li>
</ul>`
        },
        {
            id: 132,
            title: "Business Applications of Binomial Distribution",
            category: "business-binomial",
            content: `<h3><strong>Business Applications of Binomial Distribution</strong></h3>

<h4><strong>Example 1: Customer Service</strong></h4>
<p>A call center has a 70% success rate in resolving customer issues on the first call. In a day with 50 calls:</p>
<ul>
<li><strong>n = 50</strong> (number of calls)</li>
<li><strong>p = 0.70</strong> (probability of success)</li>
<li><strong>X = number of successful resolutions</strong></li>
</ul>

<p><strong>Calculations:</strong></p>
<ul>
<li><strong>Expected Value:</strong> E(X) = 50 × 0.70 = 35 successful resolutions</li>
<li><strong>Variance:</strong> Var(X) = 50 × 0.70 × 0.30 = 10.5</li>
<li><strong>Standard Deviation:</strong> σ = √10.5 = 3.24</li>
</ul>

<h5><strong>Business Questions:</strong></h5>
<ul>
<li>What's the probability of resolving at least 40 calls successfully?</li>
<li>What's the probability of resolving fewer than 30 calls successfully?</li>
<li>How many staff members are needed to handle the expected workload?</li>
</ul>

<h4><strong>Example 2: Sales Performance</strong></h4>
<p>A sales team has a 25% success rate in closing deals. Each salesperson makes 20 calls per day:</p>
<ul>
<li><strong>n = 20</strong> (number of calls)</li>
<li><strong>p = 0.25</strong> (probability of closing)</li>
<li><strong>X = number of closed deals</strong></li>
</ul>

<p><strong>Calculations:</strong></p>
<ul>
<li><strong>Expected Value:</strong> E(X) = 20 × 0.25 = 5 closed deals</li>
<li><strong>Variance:</strong> Var(X) = 20 × 0.25 × 0.75 = 3.75</li>
<li><strong>Standard Deviation:</strong> σ = √3.75 = 1.94</li>
</ul>

<h5><strong>Performance Analysis:</strong></h5>
<ul>
<li>Set realistic sales targets based on expected performance</li>
<li>Identify underperforming salespeople (below 2 standard deviations)</li>
<li>Plan resource allocation based on expected outcomes</li>
</ul>

<h4><strong>Example 3: Quality Assurance</strong></h4>
<p>A production line has a 2% defect rate. Quality control inspects 100 items:</p>
<ul>
<li><strong>n = 100</strong> (number of items inspected)</li>
<li><strong>p = 0.02</strong> (probability of defect)</li>
<li><strong>X = number of defective items</strong></li>
</ul>

<p><strong>Calculations:</strong></p>
<ul>
<li><strong>Expected Value:</strong> E(X) = 100 × 0.02 = 2 defective items</li>
<li><strong>Variance:</strong> Var(X) = 100 × 0.02 × 0.98 = 1.96</li>
<li><strong>Standard Deviation:</strong> σ = √1.96 = 1.40</li>
</ul>

<h5><strong>Quality Control Applications:</strong></h5>
<ul>
<li>Set acceptable defect limits (e.g., ≤ 5 defects)</li>
<li>Determine sample sizes for inspection</li>
<li>Monitor process stability over time</li>
<li>Compare performance across different production lines</li>
</ul>`
        }
    ]
}; 